### ISSUE TITLE
Django Taggit 5.0 is not compatible with Django <4.1

### ISSUE THREAD

**Issue by bartTC** [jazzband/django-taggit#875]
The latest [0006 migration][1] uses the `migrations.RenameIndex` method which has been [introduced in Django v4.1][2]. Running it on Django 3.2 will result in error below:

> AttributeError: module 'django.db.migrations' has no attribute 'RenameIndex'. Did you mean: 'RemoveIndex'?

The minimum Django version [here][3] should be raised accordingly to prevent installing it automatically.

[1]: https://github.com/jazzband/django-taggit/blob/master/taggit/migrations/0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx.py
[2]: https://docs.djangoproject.com/en/4.2/ref/migration-operations/#renameindex
[3]: https://github.com/jazzband/django-taggit/blob/master/setup.cfg#L37

**Comment by rtpg** [comment]
Thank you for catching this! Totally a mistake on my part.

**Comment by rtpg** [comment]
made a new release (`5.0.1`) without this issue, and looking at yanking `5.0.0` to avoid it getting proposed in Django 3.2.

**Comment by bartTC** [comment]
Thank you! Yes I think 5.0.0 should be yanked, as it is still the last version that indicates its compatible with Django 3.2.

```
❯ echo "django==3.2.22\ndjango-taggit" | pip-compile --upgrade -o /tmp/test.txt -
WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --output-file=/tmp/test.txt -
#
asgiref==3.7.2
    # via django
django==3.2.22
    # via
    #   -r -
    #   django-taggit
django-taggit==5.0.0
    # via -r -
pytz==2023.3.post1
    # via django
sqlparse==0.4.4
    # via django
```

**Comment by rtpg** [comment]
Was yanked, this should now be a non-issue
