### ISSUE TITLE
AttributeError from CommonGenericTaggedItemBase.tags_for() with current pre-release Django

### ISSUE THREAD

**Issue by philgyford** [jazzband/django-taggit#805]
I'm testing an existing, working, project with the [very latest commit](https://github.com/django/django/commit/286e7d076cfb7b4b0bdfc917de3020e6e89683f6) of Django and I'm getting an error from my custom TaggableManager that I don't get with Django 4.1. An `AttributeError` comes from `CommonGenericTaggedItemBase.tags_for()` when using `extra_filters`.

I have a `Bookmark` model that has `BookmarkTags`, though a `TaggedBookmark`:

```python
from django.db import models
from taggit.models import GenericTaggedItemBase, TagBase

class BookmarkTag(TagBase):
    # custom methods here

class TaggedBookmark(GenericTaggedItemBase):
    tag = models.ForeignKey(
        BookmarkTag,
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_items",
    )

class Bookmark(models.Model):
    is_private = models.BooleanField(default=False)
    # other fields

    tags = TaggableManager(manager=_BookmarkTaggableManager, through=TaggedBookmark)
```

The `_BookmarkTaggableManager` used is like:

```python
from django.db import models
from taggit.managers import _TaggableManager

class _BookmarkTaggableManager(_TaggableManager):

    def most_common(self):
        "Get the most common tags used on all non-private Bookmarks"

        extra_filters {"bookmark__is_private": False,}

        return (
            self.get_queryset(extra_filters)
            .annotate(num_times=models.Count(self.through.tag_relname()))
            .order_by("-num_times")
        )
```

Calling `Bookmark.tags.most_common()` has worked fine in Django 4.0 and earlier. But with the very latest Django code I get:

```
Traceback (most recent call last):
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/lib/python3.10/site-packages/taggit/managers.py", line 77, in get_queryset
    return self.instance._prefetched_objects_cache[self.prefetch_cache_name]
AttributeError: 'NoneType' object has no attribute '_prefetched_objects_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/phil/Projects/personal/django-ditto/ditto/pinboard/managers.py", line 36, in most_common
    self.get_queryset(extra_filters)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/lib/python3.10/site-packages/taggit/managers.py", line 80, in get_queryset
    return self.through.tags_for(self.model, self.instance, **kwargs).order_by(
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/lib/python3.10/site-packages/taggit/models.py", line 161, in tags_for
    return cls.tag_model().objects.filter(**kwargs).distinct()
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/query.py", line 1395, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/query.py", line 1413, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/query.py", line 1420, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/sql/query.py", line 1470, in build_filter
    col = self._get_col(targets[0], join_info.final_field, alias)
  File "/Users/phil/.local/share/virtualenvs/devproject-25a5mkZN/src/django/django/db/models/sql/query.py", line 387, in _get_col
    return target.get_col(alias, field)
AttributeError: 'ManyToManyRel' object has no attribute 'get_col'
```

I don't think I'm doing anything particularly weird?

I can't see anything obvious in the [backwards incompatible changes](https://docs.djangoproject.com/en/dev/releases/4.1/#backwards-incompatible-4-1) for Django 4.1.

The issue seems to be in [`CommonGenericTaggedItemBase.tags_for()`](https://github.com/jazzband/django-taggit/blob/master/taggit/models.py#L157). With Django 4.0 I can do this successfully:

```python
extra_filters = {"bookmark__is_private": False}
TaggedBookmark.tags_for(Bookmark, **extra_filters)
```

But if I use (what will be) Django 4.1 I get the above error ending in `AttributeError: 'ManyToManyRel' object has no attribute 'get_col'`.

If I leave the `**extra_filters` off, there is no error.

**Comment by philgyford** [comment]
I'd forgotten that there's a `CommonGenericTaggedItemBase.most_common()` method already, and that mine overrides that (I wrote this code a long time ago).

The django-taggit tests work fine with the `djmain` environments, so it's obviously a difference in my code, or else an error the existing tests don't pick up.

If I run:

```shell
tox -e py39-djmain -- tests.tests.TaggableManagerOfficialTestCase.test_most_common_extra_filters
```

 and print the `kwargs` in `CommonGenericTaggedItemBase.tags_for()` before the method's final line, it outputs:

```python
{
    'tagged_items__content_type__app_label': 'tests',
    'tagged_items__content_type__model': 'officialfood',
    'officialfood__name__in': ['pear', 'apple']
}
```

If I run one of my failing tests, and output `kwargs` at the same point in `django-taggit`, then it looks like:

```python
{
    'pinboard_taggedbookmark_items__content_type__app_label': 'pinboard',
    'pinboard_taggedbookmark_items__content_type__model': 'bookmark',
    'bookmark__is_private': False
}
```
I guess the only difference I see here is that mine is using a through model?

**Comment by philgyford** [comment]
If I remove my overridden `_BookmarkTaggableManager.most_common()` method, so that I'm using `_TaggableManager's` own one, and do this:

```python
Bookmark.tags.most_common(extra_filters={"bookmark__is_private": False})
```

I get the same error. If I don't pass `extra_filters` in, then there's no error.

**Comment by philgyford** [comment]
OK, this is now too much for anyone to read. Going to make a new issue with a minimal demonstration of the issue.
